const CATS=[['all','الكل','🛍️'],['electronics','إلكترونيات','📱'],['women','أزياء نسائية','👗'],['men','أزياء رجالية','👔'],['shoes','أحذية','👟'],['bags','حقائب','👜'],['beauty','عطور وتجميل','💄'],['home','منزل ومطبخ','🏠'],['kids','أطفال وألعاب','🧸'],['food','غذائيات','🍯'],['accessories','إكسسوارات','⌚'],['cars','سيارات وإكسسوارات','🚗'],['sport','رياضة','⚽'],['office','مكتب وقرطاسية','📚']];
const PRODUCTS=[
{id:1,c:'electronics',n:'سماعات لاسلكية Pro',p:275000,o:320000,r:4.8,e:'🎧',new:1},
{id:2,c:'women',n:'فستان نسائي أنيق',p:295000,o:360000,r:4.7,e:'👗',sale:1},
{id:3,c:'men',n:'قميص رجالي كلاسيك',p:185000,o:220000,r:4.6,e:'👔',new:1},
{id:4,c:'shoes',n:'حذاء رياضي Premium',p:420000,o:495000,r:4.9,e:'👟',sale:1},
{id:5,c:'bags',n:'حقيبة يومية فاخرة',p:260000,o:310000,r:4.7,e:'👜'},
{id:6,c:'beauty',n:'عطر شرقي فاخر',p:350000,o:410000,r:4.8,e:'🧴',new:1},
{id:7,c:'kids',n:'طقم أطفال مميز',p:175000,o:210000,r:4.5,e:'🧸'},
{id:8,c:'home',n:'طقم منزلي عصري',p:220000,o:265000,r:4.6,e:'🏠'},
{id:9,c:'food',n:'سلة غذائيات سورية',p:190000,o:225000,r:4.7,e:'🍯',sale:1},
{id:10,c:'accessories',n:'ساعة وإكسسوار أنيق',p:240000,o:290000,r:4.5,e:'⌚'},
{id:11,c:'cars',n:'إكسسوارات سيارة',p:145000,o:175000,r:4.4,e:'🚗'},
{id:12,c:'sport',n:'حقيبة رياضية',p:165000,o:200000,r:4.6,e:'🏃',new:1},
{id:13,c:'electronics',n:'شاحن سريع USB-C',p:85000,o:105000,r:4.7,e:'🔌'},
{id:14,c:'men',n:'جاكيت رجالي عصري',p:390000,o:460000,r:4.8,e:'🧥',sale:1},
{id:15,c:'women',n:'حقيبة نسائية جديدة',p:330000,o:390000,r:4.8,e:'👛',new:1},
{id:16,c:'home',n:'أداة مطبخ متعددة',p:95000,o:120000,r:4.4,e:'🍳'}];
const STORE={user:'soUserV5',cart:'soCartV5',fav:'soFavV5',orders:'soOrdersV5',addresses:'soAddressesV5',coupon:'soCouponV5'};
let state={cat:'all',query:'',sort:'default',fav:JSON.parse(localStorage.getItem(STORE.fav)||'[]'),cart:JSON.parse(localStorage.getItem(STORE.cart)||'[]')};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],fmt=n=>n.toLocaleString('ar-SY')+' ل.س';
function save(){localStorage.setItem(STORE.cart,JSON.stringify(state.cart));localStorage.setItem(STORE.fav,JSON.stringify(state.fav));updateCart()}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>$('#toast').classList.remove('show'),1700)}
function catName(id){return (CATS.find(x=>x[0]===id)||CATS[0])[1]}
function renderCats(){
 $('#catbar').innerHTML=CATS.map(x=>`<button class="${state.cat===x[0]?'active':''}" data-cat="${x[0]}">${x[2]} ${x[1]}</button>`).join('');
 $('#categoryGrid').innerHTML=CATS.slice(1).map(x=>`<button class="category" data-cat="${x[0]}"><div class="ico">${x[2]}</div><b>${x[1]}</b><span>تشكيلة متنوعة</span></button>`).join('');
 $('#drawerCats').innerHTML=CATS.slice(1).map(x=>`<button class="drawerItem" data-cat="${x[0]}">${x[2]} &nbsp; ${x[1]}</button>`).join('');
 $$('#catbar [data-cat],#categoryGrid [data-cat],#drawerCats [data-cat]').forEach(b=>b.onclick=()=>setCat(b.dataset.cat));
}
function filtered(){let a=[...PRODUCTS];if(state.cat==='sale')a=a.filter(p=>p.sale);else if(state.cat!=='all')a=a.filter(p=>p.c===state.cat);if(state.query)a=a.filter(p=>(p.n+' '+catName(p.c)).includes(state.query));if(state.sort==='low')a.sort((a,b)=>a.p-b.p);if(state.sort==='high')a.sort((a,b)=>b.p-a.p);if(state.sort==='rating')a.sort((a,b)=>b.r-a.r);return a}
function card(p){let fav=state.fav.includes(p.id);return `<article class="product"><div class="productImg">${p.e}${p.sale?'<span class="badge">خصم</span>':''}<button class="heart ${fav?'on':''}" data-fav="${p.id}">${fav?'♥':'♡'}</button></div><div class="productInfo"><span class="brandName">SYRIA ONLINE</span><h3>${p.n}</h3><div class="stars">★★★★★ <small>${p.r}</small></div><div class="priceLine"><div class="price">${fmt(p.p)} ${p.o?`<span class="old">${fmt(p.o)}</span>`:''}</div><button class="add" data-add="${p.id}">+</button></div></div></article>`}
function renderProducts(){let a=filtered();$('#productsTitle').textContent=state.query?`نتائج البحث عن «${state.query}»`:state.cat==='all'?'منتجات مختارة':state.cat==='sale'?'عروض اليوم':catName(state.cat);$('#productGrid').innerHTML=a.length?a.map(card).join(''):'<div class="empty">ما لقينا منتجات مطابقة 🔎</div>';$('#newGrid').innerHTML=PRODUCTS.filter(p=>p.new).slice(0,8).map(card).join('');$$('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));$$('[data-fav]').forEach(b=>b.onclick=()=>toggleFav(+b.dataset.fav));}
function renderChips(){let list=['all','sale','electronics','women','men','shoes','beauty','home','kids','food'];$('#chips').innerHTML=list.map(id=>`<button class="${state.cat===id?'active':''}" data-cat="${id}">${id==='sale'?'🔥 عروض':catName(id)}</button>`).join('');$$('#chips [data-cat]').forEach(b=>b.onclick=()=>setCat(b.dataset.cat))}
function setCat(c){state.cat=c;renderCats();renderChips();renderProducts();if(innerWidth<800)$('#products').scrollIntoView({behavior:'smooth',block:'start'})}
function add(id){state.cart.push({id,qty:1});save();toast('تمت إضافة المنتج إلى السلة 🛒')}
function changeQty(i,d){state.cart[i].qty+=d;if(state.cart[i].qty<1)state.cart.splice(i,1);save();openCart()}
function cartData(){return state.cart.map(x=>({x,p:PRODUCTS.find(p=>p.id===x.id)})).filter(x=>x.p)}
function updateCart(){let n=state.cart.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=n;$('#bottomCart').textContent=n;let data=cartData();$('#cartItems').innerHTML=data.length?data.map(({x,p},i)=>`<div class="cartRow"><div class="mini">${p.e}</div><div><b>${p.n}</b><div>${fmt(p.p)}</div><div class="qty"><button onclick="changeQty(${i},-1)">−</button><span>${x.qty}</span><button onclick="changeQty(${i},1)">+</button></div></div><button class="remove" onclick="removeCart(${i})">حذف</button></div>`).join(''):'<div class="empty">السلة فارغة حالياً 🛒</div>';let total=data.reduce((s,{x,p})=>s+p.p*x.qty,0);$('#cartTotal').textContent=fmt(total)}
function removeCart(i){state.cart.splice(i,1);save();openCart()}
window.changeQty=changeQty;window.removeCart=removeCart;
function openCart(){closeDrawer();$('#cartPanel').classList.add('open');updateCart()}
function closeCart(){$('#cartPanel').classList.remove('open')}
function openModal(title,body,buttons=''){ $('#modal').innerHTML=`<div class="modalHead"><h2>${title}</h2><button id="modalClose">×</button></div>${body}${buttons}`;$('#modalWrap').classList.add('open');$('#modalClose').onclick=closeModal }
function closeModal(){$('#modalWrap').classList.remove('open')}
function getUser(){try{return JSON.parse(localStorage.getItem(STORE.user)||'null')}catch{return null}}
async function hash(v){const data=new TextEncoder().encode(v);const buf=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(buf)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function account(){let u=getUser();if(!u){openModal('تسجيل الدخول / إنشاء حساب',`<div class="formGrid"><div class="field full"><label>الإيميل أو رقم الهاتف</label><input id="loginId" placeholder="example@email.com أو 09xxxxxxxx"></div><div class="field full"><label>كلمة السر</label><input id="loginPass" type="password"></div></div><div class="modalActions"><button class="primary" id="loginGo">دخول</button><button class="secondary" id="signupGo">إنشاء حساب</button></div>`);$('#loginGo').onclick=login;$('#signupGo').onclick=signup;return}openModal('حسابي',`<div class="listCard"><b>${u.name}</b><div>${u.email||u.phone||''}</div></div><div class="quick"><button data-open="orders">📦<strong>طلباتي</strong><small>الحالة والتتبع</small></button><button data-open="addresses">🏠<strong>عناويني</strong><small>إدارة العناوين</small></button></div><button class="secondary" id="logout">تسجيل الخروج</button>`);$('#logout').onclick=()=>{localStorage.removeItem(STORE.user);closeModal();toast('تم تسجيل الخروج')}}
async function login(){let id=$('#loginId').value.trim(),pass=$('#loginPass').value;if(!id||!pass)return toast('أدخل بيانات الدخول');let u=getUser();if(!u)return toast('لا يوجد حساب محفوظ على هذا الجهاز');let h=await hash(pass);if((u.email!==id&&u.phone!==id)||u.passHash!==h)return toast('بيانات الدخول غير صحيحة');closeModal();toast('أهلاً بك '+u.name)}
function signup(){openModal('إنشاء حساب جديد',`<div class="formGrid"><div class="field full"><label>الاسم الكامل</label><input id="suName"></div><div class="field"><label>الإيميل</label><input id="suEmail" type="email"></div><div class="field"><label>رقم الهاتف</label><input id="suPhone" inputmode="tel"></div><div class="field full"><label>كلمة السر</label><input id="suPass" type="password"></div></div><p style="font-size:10px;color:#7c8782">كلمة السر تُحوّل إلى SHA-256 قبل التخزين المحلي ولا تُحفظ كنص.</p><div class="modalActions"><button class="primary" id="create">إنشاء الحساب</button></div>`);$('#create').onclick=async()=>{let name=$('#suName').value.trim(),email=$('#suEmail').value.trim(),phone=$('#suPhone').value.trim(),pass=$('#suPass').value;if(!name||(!email&&!phone)||pass.length<6)return toast('أكمل البيانات وكلمة السر 6 أحرف على الأقل');localStorage.setItem(STORE.user,JSON.stringify({name,email,phone,passHash:await hash(pass)}));closeModal();toast('تم إنشاء الحساب')};}
function favorites(){let a=PRODUCTS.filter(p=>state.fav.includes(p.id));openModal('المفضلة',a.length?`<div class="productGrid">${a.map(card).join('')}</div>`:'<div class="empty">ما عندك منتجات بالمفضلة ❤️</div>');$$('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));$$('[data-fav]').forEach(b=>b.onclick=()=>{toggleFav(+b.dataset.fav);favorites()})}
function toggleFav(id){state.fav=state.fav.includes(id)?state.fav.filter(x=>x!==id):[...state.fav,id];save();renderProducts();toast(state.fav.includes(id)?'أضيف للمفضلة ❤️':'تمت الإزالة من المفضلة')}
function orders(){let a=JSON.parse(localStorage.getItem(STORE.orders)||'[]');openModal('طلباتي',a.length?a.map(o=>`<div class="listCard"><b>${o.id}</b> <span class="pill">${o.status}</span><div>${o.name} — ${o.phone}</div><div>${o.city} — ${o.address}</div><small>${new Date(o.date).toLocaleString('ar-SY')}</small></div>`).join(''):'<div class="empty">لا توجد طلبات بعد 📦</div>')}
function addresses(){let a=JSON.parse(localStorage.getItem(STORE.addresses)||'[]');openModal('عناويني',`${a.map((x,i)=>`<div class="listCard"><b>${x.title}</b><div>${x.city} — ${x.address}</div><button class="secondary" onclick="delAddress(${i})">حذف</button></div>`).join('')}<div class="modalActions"><button class="primary" id="addAddress">+ إضافة عنوان</button></div>`);$('#addAddress').onclick=addAddress}
function addAddress(){openModal('إضافة عنوان',`<div class="formGrid"><div class="field"><label>اسم العنوان</label><input id="at"></div><div class="field"><label>المحافظة / المدينة</label><input id="ac"></div><div class="field full"><label>العنوان بالتفصيل</label><textarea id="aa" rows="3"></textarea></div></div><div class="modalActions"><button class="primary" id="saveAddress">حفظ</button></div>`);$('#saveAddress').onclick=()=>{let a=JSON.parse(localStorage.getItem(STORE.addresses)||'[]');a.push({title:$('#at').value||'عنوان',city:$('#ac').value,address:$('#aa').value});localStorage.setItem(STORE.addresses,JSON.stringify(a));addresses()}}
window.delAddress=i=>{let a=JSON.parse(localStorage.getItem(STORE.addresses)||'[]');a.splice(i,1);localStorage.setItem(STORE.addresses,JSON.stringify(a));addresses()};
function checkout(){if(!state.cart.length)return toast('السلة فارغة');if(!getUser())return account();let u=getUser();openModal('إتمام الطلب',`<div class="formGrid"><div class="field full"><label>الاسم الكامل</label><input id="coName" value="${u.name||''}"></div><div class="field"><label>رقم الهاتف</label><input id="coPhone" value="${u.phone||''}"></div><div class="field"><label>المحافظة / المدينة</label><input id="coCity"></div><div class="field full"><label>العنوان بالتفصيل</label><textarea id="coAddress" rows="3"></textarea></div><div class="field full"><label>ملاحظات للطلب</label><textarea id="coNotes" rows="2"></textarea></div><div class="field"><label>الكوبون</label><input id="coCoupon" placeholder="مثلاً SAVE10"></div></div><div class="modalActions"><button class="primary" id="confirmOrder">تأكيد الطلب</button></div>`);$('#confirmOrder').onclick=()=>{let name=$('#coName').value,phone=$('#coPhone').value,city=$('#coCity').value,address=$('#coAddress').value;if(!name||!phone||!city||!address)return toast('أكمل بيانات التوصيل');let os=JSON.parse(localStorage.getItem(STORE.orders)||'[]');os.unshift({id:'SO-'+Date.now().toString().slice(-7),date:new Date().toISOString(),name,phone,city,address,notes:$('#coNotes').value,status:'جديد',items:state.cart});localStorage.setItem(STORE.orders,JSON.stringify(os));state.cart=[];save();closeModal();closeCart();toast('تم تسجيل الطلب بنجاح 📦');setTimeout(orders,400)}}
function filterModal(){openModal('بحث وفلترة',`<div class="formGrid"><div class="field full"><label>بحث</label><input id="fmSearch" value="${state.query}"></div><div class="field"><label>القسم</label><select id="fmCat">${CATS.map(x=>`<option value="${x[0]}" ${state.cat===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></div><div class="field"><label>الترتيب</label><select id="fmSort"><option value="default">افتراضي</option><option value="low">الأرخص</option><option value="high">الأغلى</option><option value="rating">الأعلى تقييماً</option></select></div></div><div class="modalActions"><button class="primary" id="applyFilter">تطبيق</button></div>`);$('#fmSort').value=state.sort;$('#applyFilter').onclick=()=>{state.query=$('#fmSearch').value.trim();state.cat=$('#fmCat').value;state.sort=$('#fmSort').value;closeModal();renderCats();renderChips();renderProducts();$('#products').scrollIntoView({behavior:'smooth'})}}
function openBy(name){if(name==='cart')openCart();else if(name==='account')account();else if(name==='favorites')favorites();else if(name==='orders')orders();else if(name==='addresses')addresses();else if(name==='filter')filterModal();else if(name==='categories')$('#categories').scrollIntoView({behavior:'smooth'})}
function closeDrawer(){ $('#drawer').classList.remove('open');$('#overlay').classList.remove('show') }
$('#menuBtn').onclick=()=>{$('#drawer').classList.add('open');$('#overlay').classList.add('show')};$('#closeDrawer').onclick=closeDrawer;$('#overlay').onclick=()=>{closeDrawer();closeCart()};$('#cartBtn').onclick=openCart;$('#checkoutBtn').onclick=checkout;$('#accountBtn').onclick=account;$('#favBtn').onclick=favorites;$('#filterBtn').onclick=filterModal;$('#sort').onchange=e=>{state.sort=e.target.value;renderProducts()};$('#searchBtn').onclick=()=>{state.query=$('#search').value.trim();renderProducts();$('#products').scrollIntoView({behavior:'smooth'})};$('#search').onkeydown=e=>{if(e.key==='Enter')$('#searchBtn').click()};$('#modalWrap').onclick=e=>{if(e.target.id==='modalWrap')closeModal()};document.body.onclick=e=>{let b=e.target.closest('[data-open]');if(b)openBy(b.dataset.open);let s=e.target.closest('[data-scroll]');if(s){let el=$('#'+s.dataset.scroll);if(el)el.scrollIntoView({behavior:'smooth'})}};
renderCats();renderChips();renderProducts();updateCart();
